"""Rule repositories: HANA-backed and in-memory."""

from __future__ import annotations

import logging
import time
from abc import ABC, abstractmethod
from typing import Optional

from src.config import Config
from src.exceptions import RuleExecutionError


logger = logging.getLogger(__name__)


class RuleRepository(ABC):
    @abstractmethod
    def get_code(self, ruleid: str) -> Optional[str]:
        raise NotImplementedError

    @abstractmethod
    def check_health(self) -> bool:
        raise NotImplementedError

    @abstractmethod
    def set_skip_override(
        self,
        spaceid: str,
        taskchain: str,
        stepid: str,
        step_to_be_checked: str,
        override: bool,
    ) -> None:
        raise NotImplementedError


class HanaRuleRepository(RuleRepository):
    """SAP HANA-backed rule repository.

    Expects table generated by CDS: CONDITIONAL_APP_RULES_RULETABLE.
    """

    TABLE_NAME = "CONDITIONAL_APP_RULES_RULETABLE"

    def __init__(self, credentials: dict | None = None):
        self._credentials = credentials or Config.get_hana_credentials()
        logger.info("HanaRuleRepository initialized")

    def _get_connection(self):
        # Lazy import so local dev/tests don't require hdbcli.
        try:
            from hdbcli import dbapi  # type: ignore
        except Exception as e:
            raise RuntimeError("hdbcli not available; install SAP HANA client driver") from e

        conn_params = {
            "address": self._credentials["host"],
            "port": int(self._credentials["port"]),
            "user": self._credentials["user"],
            "password": self._credentials["password"],
            "encrypt": self._credentials.get("encrypt", True),
        }
        if self._credentials.get("schema"):
            conn_params["currentschema"] = self._credentials["schema"]

        return dbapi.connect(**conn_params)

    def get_code(self, ruleid: str) -> Optional[str]:
        try:
            rule_number = int(ruleid)
        except ValueError:
            logger.warning("Invalid ruleid '%s' - must be an integer", ruleid)
            return None

        conn = None
        try:
            conn = self._get_connection()
            cursor = conn.cursor()
            cursor.execute(f"SELECT RULE FROM {self.TABLE_NAME} WHERE RULENUMBER = ?", (rule_number,))
            row = cursor.fetchone()
            cursor.close()
            return row[0] if row else None
        finally:
            if conn:
                conn.close()

    def check_health(self) -> bool:
        conn = None
        try:
            conn = self._get_connection()
            cursor = conn.cursor()
            cursor.execute("SELECT 1 FROM DUMMY")
            cursor.fetchone()
            cursor.close()
            return True
        except Exception as e:
            logger.error("HANA health check failed: %s", e)
            return False
        finally:
            if conn:
                conn.close()

    def set_skip_override(
        self,
        spaceid: str,
        taskchain: str,
        stepid: str,
        step_to_be_checked: str,
        override: bool,
    ) -> None:
        conn = None
        try:
            conn = self._get_connection()
            cursor = conn.cursor()
            if override:
                cursor.execute(
                    "UPDATE CONDITIONAL_APP_TASKCHAINS_SKIPOVERRIDE "
                    "SET OVERRIDE = ? "
                    "WHERE SPACEID = ? AND TASKCHAIN = ? AND STEPID = ? AND STEPTOBECHECKED = ?",
                    (1, spaceid, taskchain, stepid, step_to_be_checked),
                )
            else:
                cursor.execute(
                    "UPDATE CONDITIONAL_APP_TASKCHAINS_SKIPOVERRIDE "
                    "SET OVERRIDE = ?, LASTOVERRIDEAT = CURRENT_TIMESTAMP "
                    "WHERE SPACEID = ? AND TASKCHAIN = ? AND STEPID = ? AND STEPTOBECHECKED = ?",
                    (0, spaceid, taskchain, stepid, step_to_be_checked),
                )
            conn.commit()
            cursor.close()
        finally:
            if conn:
                conn.close()

    def query(self, sql: str, params: tuple = None) -> list:  # type: ignore
        sql_upper = sql.strip().upper()
        if not sql_upper.startswith("SELECT"):
            raise ValueError("Only SELECT queries are allowed")

        forbidden = ["INSERT", "UPDATE", "DELETE", "DROP", "CREATE", "ALTER", "TRUNCATE", "GRANT", "REVOKE", "EXEC"]
        for keyword in forbidden:
            if keyword in sql_upper:
                raise ValueError(f"Forbidden keyword '{keyword}' in query")

        conn = None
        try:
            conn = self._get_connection()
            cursor = conn.cursor()
            cursor.execute(sql, params or ())
            columns = [desc[0] for desc in cursor.description]
            rows = cursor.fetchall()
            cursor.close()
            return [dict(zip(columns, row)) for row in rows]
        except ValueError:
            raise
        except Exception as e:
            raise RuleExecutionError(f"Database query failed: {e}")
        finally:
            if conn:
                conn.close()


class InMemoryRuleRepository(RuleRepository):
    def __init__(self, rules: dict[str, str] | None = None):
        self._rules = rules or {}

    def add_rule(self, ruleid: str, code: str) -> None:
        self._rules[ruleid] = code

    def get_code(self, ruleid: str) -> Optional[str]:
        return self._rules.get(ruleid)

    def check_health(self) -> bool:
        return True

    def set_skip_override(
        self,
        spaceid: str,
        taskchain: str,
        stepid: str,
        step_to_be_checked: str,
        override: bool,
    ) -> None:
        key = (spaceid, taskchain, stepid, step_to_be_checked)
        store = getattr(self, "_skip_overrides", {})
        store[key] = {
            "override": override,
            "lastOverrideAt": time.time() if not override else store.get(key, {}).get("lastOverrideAt"),
        }
        self._skip_overrides = store

    def query(self, sql: str, params: tuple = None) -> list:  # type: ignore
        sql_upper = sql.strip().upper()
        if not sql_upper.startswith("SELECT"):
            raise ValueError("Only SELECT queries are allowed")

        forbidden = ["INSERT", "UPDATE", "DELETE", "DROP", "CREATE", "ALTER", "TRUNCATE", "GRANT", "REVOKE", "EXEC"]
        for keyword in forbidden:
            if keyword in sql_upper:
                raise ValueError(f"Forbidden keyword '{keyword}' in query")

        return getattr(self, "_mock_query_result", [])

    def set_query_result(self, result: list) -> None:
        self._mock_query_result = result
